WebUI/WebUI/Controllers/BookAdditionalController.cs
using Arch.EntityFrameworkCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using BookStore.Entities.BookAdditionals;
using BookStore.Entities.Products;

namespace WebUI.Controllers
{
    public class BookAdditionalController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BookAdditionalController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Author(int id)
        {
            Author author = _unitOfWork.GetRepository<Author>().GetAll()
                .Where(el => el.ID == id).FirstOrDefault();
            ViewBag.Books = _unitOfWork.GetRepository<Book>().GetAll()
                .Where(book => book.AuthorId == id);
            return View(author);
        }
    }
}

WebUI/WebUI/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Arch.EntityFrameworkCore.UnitOfWork;
using BookStore.Entities.Products;
using BookStore.Entities.BaseObjects;
using BookStore.Entities.BookAdditionals;
namespace WebUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ProductController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var product = _unitOfWork.GetRepository<ProductObject>().GetAll().Where(product => !product.isArchived);
            return View(product);
        }

        [HttpGet]
        public IActionResult Book(int id)
        {
            Book book = _unitOfWork.GetRepository<Book>().GetAll()
                .Where(book => book.ID == id).First();
            book.Author = _unitOfWork.GetRepository<Author>().GetAll().Where(author => author.ID == book.AuthorId).First();
            book.Jenre = _unitOfWork.GetRepository<Jenre>().GetAll().Where(jenre => jenre.ID == book.JenreId).First();
            return View(book);
        }
    }
}

WebUI/WebUI/Views/Product/Book.cshtml
@model BookStore.Entities.Products.Book

<br />
<div class="container">
    <div class="row">
        <div class="col-4">
            <img class="w-100 rounded" src="@Model.PhotoLink"/>
        </div>
        <div class="col-8">
            <div class="display-3">@Model.Name</div>
            <h5><a href="@Url.Action("Author", "BookAdditional", new {id = @Model.AuthorId})">@Model.Author.Name</a></h5>
            <br />
            <ul>
                @if(Model.Publisher != null) 
                    {<li>Издатель: @Model.Publisher</li>}
                @if(Model.YearOfPublishing != null) 
                    {<li>Год издания: @Model.YearOfPublishing</li>}
                @if(Model.ISBN != null) 
                    {<li>ISBN: @Model.ISBN</li>}
                @if(Model.NumberOfPages != null) 
                    {<li>Количество страниц: @Model.NumberOfPages</li>}
                @if(Model.Circulation != null) 
                    {<li>Тираж: @Model.Circulation</li>}
                @if(Model.Jenre.Name != null) 
                    {<li>Жанр: <a>@Model.Jenre.Name</a></li>}
                @if(Model.Weight != null) 
                    {<li>Вес: @Model.Weight г.</li>}
                @if(Model.Format != null) 
                    {<li>Размер: @Model.Format</li>}
            </ul>
            <br />
            <h2 class="d-inline-block"><span class="badge badge-primary">@Model.Cost р.</span></h2>
            <button type="button" class="btn btn-primary d-inline-block float-right">В корзину</button>
            <br />
        </div>
    </div>
</div>

WebUI/WebUI/Views/Product/Index.cshtml
@model IEnumerable<BookStore.Entities.BaseObjects.ProductObject>

<div class="container">
    <br />
    <h1 class="display-5 ">Все продукты:</h1>
    <div class="row bg-light">
        @foreach(var product in Model)
        {
            <div class="col-2 rounded p-3" style="height: 240px;">
                <div class="" style="background-image: url(@product.PhotoLink); height: 80%; width: inherit; background-size:cover; background-repeat:no-repeat;"> </div>
                <div>@product.Name</div>
                <div>@product.Cost</div>
            </div>
        }
    </div>
</div>