WebUI/WebUI/Controllers/AdminController.cs
using Arch.EntityFrameworkCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using BookStore.Entities.BaseObjects;
using BookStore.Entities.Products;
using BookStore.Entities.BookAdditionals;
using Microsoft.AspNetCore.Authorization;
using BookStore.Entities.Accounting;

namespace WebUI.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AdminController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Book()
        {
            ViewBag.Jenres = _unitOfWork.GetRepository<Jenre>().GetAll();
            ViewBag.Authors = _unitOfWork.GetRepository<Author>().GetAll();
            ViewBag.Books = _unitOfWork.GetRepository<Book>().GetAll();
            return View();
        }

        [HttpPost]
        public string Book(Book book)
        {
            _unitOfWork.GetRepository<Book>().Insert(book);
            _unitOfWork.SaveChanges();


            return "Добавлено!";
        }


        [HttpGet]
        public IActionResult Jenre()
        {
            ViewBag.Jenres = _unitOfWork.GetRepository<Jenre>().GetAll();
            return View();
        }

        [HttpPost]
        public string Jenre(Jenre jenre)
        {
            _unitOfWork.GetRepository<Jenre>().Insert(jenre);
            _unitOfWork.SaveChanges();


            return "Добавлено!";
        }


        [HttpGet]
        public IActionResult Author()
        {
            ViewBag.Authors = _unitOfWork.GetRepository<Author>().GetAll();
            return View();
        }

        [HttpPost]
        public string Author(Author author)
        {
            _unitOfWork.GetRepository<Author>().Insert(author);
            _unitOfWork.SaveChanges();


            return "Добавлено!";
        }

        [HttpGet]
        public IActionResult User()
        {
            ViewBag.Roles = _unitOfWork.GetRepository<Role>().GetAll();
            ViewBag.Users = _unitOfWork.GetRepository<User>().GetAll();
            return View();
        }

        [HttpPost]
        public string User(User user)
        {
            _unitOfWork.GetRepository<User>().Insert(user);
            _unitOfWork.SaveChanges();


            return "Добавлено!";
        }

        [HttpGet]
        public IActionResult Role()
        {
            ViewBag.Roles = _unitOfWork.GetRepository<Role>().GetAll();
            return View();
        }

        [HttpPost]
        public string Role(Role role)
        {
            _unitOfWork.GetRepository<Role>().Insert(role);
            _unitOfWork.SaveChanges();


            return "Добавлено!";
        }

    }
}

WebUI/WebUI/Controllers/CatalogController.cs
using Arch.EntityFrameworkCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using BookStore.Entities.Products;

namespace WebUI.Controllers
{
    public class CatalogController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private int pageSize = 50;

        public CatalogController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult BookCatalog(int page = 1)
        {
            var books = _unitOfWork.GetRepository<Book>().GetAll()
                .Skip((page - 1) * pageSize).Take(pageSize);

            return View(books);
        }
    }
}

WebUI/WebUI/Views/Shared/_BaseLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link type="text/css" href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/lib/slick-1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="~/lib/slick-1.8.1/slick/slick-theme.css"/>
</head>
<body>
    <header class="container-fluid bg-info p-2">
        <h1 class="d-inline-block"><a class="text-decoration-none text-white"href="@Url.Action("Index", "Home")">Книжный погребок</a></h1>
        <nav class="d-inline-block float-right p-3">
            @if(User.IsInRole("admin"))
                {<a href="@Url.Action("Index", "Admin")" class="text-white ml-3">Админка</a>}
            <a href="@Url.Action("BookCatalog", "Catalog")" class="text-white ml-3">Книги</a>
            <a href="@Url.Action("Cart", "Account")" class="text-white ml-3">Корзина</a>
            @if (User.Identity.IsAuthenticated)
            {
                <a href="@Url.Action("Profile", "Account")" class="text-white ml-3">Мой профиль</a>
                <a href="@Url.Action("Logout", "Account")" class="text-white ml-3">Выйти</a>
            }
            else
            {
                <a href="@Url.Action("Login", "Account")" class="text-white ml-3">Войти</a>
                <a href="@Url.Action("Register", "Account")" class="text-white ml-3">Зарегистрироваться</a>
            }
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>

    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/slick-1.8.1/slick/slick.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function(){
           $('.multiple-items').slick({
      infinite: true,
      dots: true,
      slidesToShow: 5,
      slidesToScroll: 1
    });
    });
  </script>
</body>
</html>